INSERT  INTO
	cms_article
      ( 
      id                            
      ,title                          
      ,image_href                     
      ,summary                        
      ,content                        
      ,column_id                      
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,publish                        
      ,PUBLISH_DATE                   
      ,AUTHOR                         
      ,LABEL
      ,SERIAL_NUMBER
      ,code
      ,is_link                        
      ,link
      ,is_show
      ,dept_id
      ,xcx_id
      ) 
values
      (
      :cmsArticle.id                            
      ,:cmsArticle.title                         
      ,:cmsArticle.imageHref                     
      ,:cmsArticle.summary                       
      ,:cmsArticle.content                       
      ,:cmsArticle.columnId                      
      ,:cmsArticle.createName                    
      ,:cmsArticle.createBy                      
      ,:cmsArticle.createDate                    
      ,:cmsArticle.publish                       
      ,:cmsArticle.publishDate                   
      ,:cmsArticle.author                        
      ,:cmsArticle.label
      ,:cmsArticle.serialNumber
      ,:cmsArticle.code
      ,:cmsArticle.isLink                        
      ,:cmsArticle.link
      ,:cmsArticle.isShow
      ,:cmsArticle.deptId
      ,:cmsArticle.xcxId
      )